GET http://localhost:3000

###

POST http://localhost:3000/auth/login

@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo/

# RECADOS
###
GET {{baseUrl}}/recados/
###
GET {{baseUrl}}/recados/1/


#CARROS
###

GET {{baseUrl}}/carros/

###
GET {{baseUrl}}/carros/1/

