GET http://localhost:3000

###

POST http://localhost:3000/auth/login

@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo/

# RECADOS
###
GET {{baseUrl}}/recados/
###
GET {{baseUrl}}/recados/1/

###

POST {{baseUrl}}/recados/

Content-Type: application/json

{
    "recado" : "this is the message i am setting",
    "nova-chave" : "outro valor"
}

PATCH  {{baseUrl}}/recados/1/

Content-Type: application/json

{
    "recado" : "this is the message i am setting",
    "nova-chave" : "outro valor"
}